apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: vprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached
        ports:
        - containerPort: 11211