apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-web
  namespace: vprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vprofile-web
  template:
    metadata:
      labels:
        app: vprofile-web
    spec:
      containers:
      - name: vprofile-web
        image: vprocontainers/vprofileweb
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vprofile-web
  namespace: vprofile
spec:
  type: LoadBalancer
  selector:
    app: vprofile-web
  ports:
  - port: 80
    targetPort: 80